### ISSUE TITLE
OHC and OHA should both redirect to same calendar

### ISSUE THREAD

**Issue by ErinOHMin** [OuachitaHillsMinistries/wp-oh-theme#50]

**Comment by narthur** [comment]
Can you describe this a little more? Is this referring to the links in the navigation pointing to one page?

**Comment by ErinOHMin** [comment]
Yes, I think that would be the easiest thing.

**Comment by narthur** [comment]
Ok. There's a section in the sidebar when the new OH theme is applied called "Global Pages." Global pages always appear in the navigation. Will that do the trick?

**Comment by ErinOHMin** [comment]
Maybe. I'll look at how the calendar page gets set up within the plugin itself. Thanks!
